### ISSUE TITLE
Sessions 関連の多言語対応（初期リリース分）

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#141]

**Comment by keitokusano** [comment]
@Kurogoma4D CC: @blendthink @TK-Guitar 
Sessions 関連の初期リリースに必要な多言語対応ですが、他にもありますでしょうか？
以下の画面はすでに対応されているように見えました。
- [Sessions](https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=1063-3942&node-type=frame&t=24kFqg2ZkJFobzgL-0)
- [Bookmarked sessions](https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=1134-4442&node-type=frame&t=24kFqg2ZkJFobzgL-0)（英語：Bookmarked 日本語：お気に入り）
- [Session detail](https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=709-2307&node-type=frame&t=24kFqg2ZkJFobzgL-0)

Sessions 画面
| 日本語 | 英語 | Design |
|-|-|-|
| <img src="https://github.com/user-attachments/assets/b041fcc5-7424-40af-9a4a-81d76bc1bf4d" width="300" />  | <img src="https://github.com/user-attachments/assets/afae793e-3fed-4466-af54-6ceef0911396" width="300" /> | <img src="https://github.com/user-attachments/assets/29317ba4-0fbf-4d4e-b071-df7d25688186" width="300" /> | 


Bookmarked sessions 画面
| 日本語 | 英語 | Design |
|-|-|-|
| <img src="https://github.com/user-attachments/assets/4f15d55f-bfc0-4b94-8289-837bff7d6418" width="300" />  | <img src="https://github.com/user-attachments/assets/e5b38237-455e-4f30-b5ac-03aa1c57bf39" width="300" /> | <img src="https://github.com/user-attachments/assets/d428d238-6013-4fe2-a9f8-887bc67d7969" width="300" /> | 

Session detail 画面
| 日本語 | 英語 | Design |
|-|-|-|
| <img src="https://github.com/user-attachments/assets/4b0d875c-c607-4781-89c8-2790a4f2700d" width="300" />  | <img src="https://github.com/user-attachments/assets/978136df-c8b4-4728-9195-6946c0881f10" width="300" /> | <img src="https://github.com/user-attachments/assets/c33e3d3a-eb22-4feb-b183-d48dc8a9f83b" width="300" /> | 
| <img src="https://github.com/user-attachments/assets/167027ce-7ca4-4182-9ed3-94430592235a" width="300" />  | <img src="https://github.com/user-attachments/assets/42876465-8bd8-417d-bdac-9e474f70f2d6" width="300" /> | <img src="https://github.com/user-attachments/assets/c33e3d3a-eb22-4feb-b183-d48dc8a9f83b" width="300" /> | 
| <img src="https://github.com/user-attachments/assets/1555639d-145f-4047-9bba-08697dc4caee" width="300" />  | <img src="https://github.com/user-attachments/assets/934445f4-27c0-440f-9d93-d8f203cc1ae8" width="300" /> | <img src="https://github.com/user-attachments/assets/c33e3d3a-eb22-4feb-b183-d48dc8a9f83b" width="300" /> | 

Session arbファイル
<img width="1510" alt="Session-arbファイル" src="https://github.com/user-attachments/assets/f5ef2604-8d76-45fa-9033-051125012095">

**Comment by Kurogoma4D** [comment]
現状で問題ないかと思います🙆

**Comment by keitokusano** [comment]
ありがとうございます！
では Close とさせていただきます。
