### ISSUE TITLE
Venue 関連の多言語対応（初期リリース分）

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#142]

**Comment by keitokusano** [comment]
@Kurogoma4D CC: @blendthink @TK-Guitar 
Venue 関連の初期リリースに必要な多言語対応ですが、何かありますでしょうか？
[Figma](https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=709-2365&node-type=frame&t=24kFqg2ZkJFobzgL-0)を拝見したのですが、分かりませんでした。

**Comment by Kurogoma4D** [comment]
こちらは現状特に対応することはなく、フロアマップのデータが用意でき次第必要なところを実装する形になるかと思います（なのでcloseしちゃってもいいかと）。

**Comment by keitokusano** [comment]
ありがとうございます！
では、Close させていただきます。
