### ISSUE TITLE
News 関連の多言語対応（初期リリース分）

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#143]

**Comment by keitokusano** [comment]
@Kurogoma4D CC: @blendthink 
News 関連の初期リリースに必要な多言語対応ですが、他にもありますでしょうか？

| 英語 | 日本語 | 現在のarbファイル |
|-|-|-|
| <img src="https://github.com/user-attachments/assets/d246bf81-eb1e-45d6-a4df-e74696f49c14" width="300" />  | <img src="https://github.com/user-attachments/assets/e594e875-3fb2-408f-b120-1efc046e54b5" width="300" /> | <img src="https://github.com/user-attachments/assets/07d7eb2d-c2df-459b-be57-bdcf88097000" width="300" /> | 

[Figma](https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=709-2615&node-type=frame&t=wQ4b9WpyLSRKgDoz-0)を拝見する限りですと、初期リリース対応分は足りているように見えたので、お伺いした次第です。

**Comment by Kurogoma4D** [comment]
現状で問題ないかと思います！
強いて言うなら、日本語の方で「ニュース」が「お知らせ」になっているとより良いかなと思います🧐

**Comment by keitokusano** [comment]
@Kurogoma4D 
ありがとうございます！
では、せっかくなのでそちらの対応を入れたいと思います(*´ω｀*)
