### ISSUE TITLE
About us 関連の多言語対応（初期リリース分）

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#144]

**Comment by Kurogoma4D** [comment]
- 見出しのテキストスタイル変更
  - `title/medium` → `title/large`
- 「コントリビューター」→ 「Contributors」

**Comment by keitokusano** [comment]
対応 commit は以下の通りです。（チーム相談済み）
https://github.com/FlutterKaigi/2024/commit/ea47ee9fe46b22d5bd889a02d62ab9176184ebf8
https://github.com/FlutterKaigi/2024/commit/b031f4c6beab0c556448d5a4601aa003680d63cb
https://github.com/FlutterKaigi/2024/commit/6523b4a3ef497b22266a8b857d09631ae5e7fe2a
