### ISSUE TITLE
[Website-Staff]: Sponsor一覧の作成 [UI] 

### ISSUE THREAD

**Issue by YumNumm** [FlutterKaigi/2024#148]
> [!WARNING]
> **8月中には完成させる必要があります。**
> (契約の関係で9月中にはロゴを掲載する必要があります。 余裕を持って8月中には終わらせたい)
> 早く実装が完了する分には大歓迎です

### 概要

- スポンサー一覧の作成
  - Figmaを参照してください

- 想定されるInput
  - `Sponsor class`
    - `String imageUrl`

### 参考文献

UI: https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=800-713&t=Nz9SXSFJCWyB35xH-4

**Comment by blendthink** [comment]
@YumNumm 
こちら対応済みだと思いますので、クローズしておきます、、！
