### ISSUE TITLE
[Website-Staff]: お知らせ機能のUI+Data実装

### ISSUE THREAD

**Issue by YumNumm** [FlutterKaigi/2024#153]
### 概要

- お知らせ(News)機能
  - データチームが提供するAPIからNewsの配列を非同期で取得し、保持
  - UI
    - https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=138-47&t=Nz9SXSFJCWyB35xH-4

### 参考文献

- depends on #90

**Comment by blendthink** [comment]
@YumNumm 
こちらは対応済みだと思いますのでクローズしてしまいます！
