### ISSUE TITLE
[Website-Staff]: Speaker WantedのUI実装

### ISSUE THREAD

**Issue by YumNumm** [FlutterKaigi/2024#154]
### 概要

> [!WARNING] 
> 8/6にリリースするため、7月中には実装を完了してください

- Speaker Wanted部分のUI
  - 

### 参考文献

https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=764-321&t=Nz9SXSFJCWyB35xH-4

**Comment by blendthink** [comment]
@YumNumm 
こちら対応済みだと思いますので、クローズしておきます、、！
