### ISSUE TITLE
[App-Staff]: 会場案内図

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#30]
### 達成したいこと

会場の詳しい情報や行き方を確認することができる。

### 可能であれば

３Dデータ作成して埋め込むなど、よりリッチにする。
Vertex Shader を使用するといいかもしれない。

### 参考文献

- https://github.com/orgs/flutter/projects/134/views/1
- https://github.com/flutter/flutter/wiki/Flutter-GPU

**Comment by Kurogoma4D** [comment]
https://github.com/FlutterKaigi/2024/issues/165 で対応したのでclose
