### ISSUE TITLE
[App-Staff]: やさしい日本語の対応の進め方について調査・検討

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#34]
### 概要

- やさしい日本語の対応を進めたいが、可能な限り自動化していきたい
- CI でドキュメントや文言リソースの自動チェック・校正ができると嬉しい

### 参考文献

- http://www4414uj.sakura.ne.jp/Yasanichi1/nsindan/
- https://tsutaeru.cloud/translation/try.html
- https://qiita.com/azu/items/623e5f50ccac2d4a8ac8

**Comment by koji-1009** [comment]
一旦、[JTF日本語標準スタイルガイド（翻訳用）](https://www.jtf.jp/tips/styleguide)をベースにするのが、読みやすい日本語として統一できるのではないかと考えました。

https://github.com/textlint-ja/textlint-rule-preset-JTF-style

**Comment by koji-1009** [comment]
残タスクとしては、下記のルールの追加を判断します。

- https://github.com/textlint-ja/textlint-rule-no-synonyms
  - 文章中の同義語を表記ゆれをチェックするtextlintルール
- https://github.com/textlint-ja/textlint-rule-ja-no-successive-word
  - 同一の単語（厳密には形態素解析した結果のToken）が間違えて連続しているのを見つけるtextlintルール
- https://github.com/textlint-ja/textlint-rule-ja-no-orthographic-variants
  - 表記ゆれをチェックする textlint ルール
- https://github.com/textlint-ja/textlint-rule-ja-no-inappropriate-words
  - 不適切表現をチェックするtextlintルール
- https://github.com/textlint-ja/textlint-rule-ja-unnatural-alphabet
  - 不自然なアルファベットを検知する[textlint](https://github.com/textlint/textlint)ルール。

@blendthink 
上記のルールを眺める限り、やさしい日本語への対応としては、直接的につながるものではないかなと思います。
一方で、表記揺れのチェックなどは、アプリケーション内の日本語の読みやすさにつながるのかなと。この点、どのように考えると良いでしょうか？

**Comment by blendthink** [comment]
@koji-1009 
返信遅くなりました🙏 
個人的には、いったん良さそうなものは入れてしまって、もし期待する効果とは違う結果になってしまったり、メリットよりデメリット（時間かかりすぎるなど）が大きくなってしまったりしたらルールから外せばいいかなと思いました💡

**Comment by koji-1009** [comment]
@blendthink 
確認ありがとうございます！ では、こちらの5ルールを追加して、本issueは一旦完了とさせていただければと！
