### ISSUE TITLE
[App-Staff]: フロアガイド

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#36]
### 達成したいこと

受付・セッション・ブース・お手洗い・出入り口などの場所を確認することができる。

**Comment by blendthink** [comment]
いったんは画像を表示するだけでもいいかも
拡大縮小はあとからでもOK。実装してしまってもOK

**Comment by Kurogoma4D** [comment]
画像：
https://www.figma.com/design/kCdYJWIgR0dOrJWrBvcqlE/FlutterKaigi-Floor-Design?node-id=140-5&t=lUjqbGhcavfeW50t-4

**Comment by keitokusano** [comment]
もし可能なら webp にしてみる。（文字崩れとかあれば、 png でOK）
