### ISSUE TITLE
[App-Staff]: コントリビューター一覧

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#37]
### 達成したいこと

どのような人たちがコントリビュートしたかざっくり知ることができる。

**Comment by TK-Guitar** [comment]
https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=425-5994&t=OTXtu337Cx9sZZBX-0
