### ISSUE TITLE
[Contributor]: セッション詳細画面から該当のセッションをカレンダーに登録できるようにする

### ISSUE THREAD

**Issue by Kurogoma4D** [FlutterKaigi/2024#379]
### 関連するもの

App

### タスクの種類

Feature

### 概要

セッション詳細画面にある日時欄をタップすると、該当するセッションの予定をカレンダーアプリに登録できる機能を追加します。
動作イメージとしては以下の通りです。

1. 下記の該当箇所をタップする
2. AndroidではGoogleカレンダー、iOSでは標準のカレンダーAppで予定のタイトル、日時、場所（ルーム名）が埋まった状態のViewが表示される
3. そのまま自身の予定として登録できる

該当箇所：
<img width="743" alt="image" src="https://github.com/user-attachments/assets/bcde03d3-3160-457b-912b-0d76b0a1820f">

### 参考文献

FlutterKaigi 2023公式アプリでの実装 https://github.com/FlutterKaigi/conference-app-2023/pull/250

**Comment by Kurogoma4D** [comment]
このタスクはコアスタッフのタスク #231 がcloseしたら着手可能になります。

**Comment by blendthink** [comment]
詳しい実装については #418 を参考にしてください。

**Comment by blendthink** [comment]
こちらで対応済みのためクローズします🙏
https://github.com/FlutterKaigi/2024/pull/501
