### ISSUE TITLE
[App-Staff]: スタッフ一覧

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#38]
### 達成したいこと

どのような人たちがスタッフとして活動したかざっくり知ることができる。

**Comment by TK-Guitar** [comment]
https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=425-657&t=OTXtu337Cx9sZZBX-0
