### ISSUE TITLE
[Contributor]: ニュース一覧画面で適切なフィルタリング処理を実装する

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#381]
### 関連するもの

App

### タスクの種類

Bug

### 概要

アプリのニュース一覧画面で現在適切なフィルタリング処理を実装してください。
具体的にはニュースが現在の時刻において有効であるかどうかを確認します。有効でない場合には表示しないようにフィルタリングしてください。

有効であるためには、以下の2つの条件を満たしている必要があります:
- ニュースがすでに始まっている（開始時刻が現在より前）。
- ニュースがまだ終了していない（終了時刻が現在より後、もしくは終了時刻が指定されていない）。

### 参考文献

https://github.com/FlutterKaigi/2024/blob/8195a664dedb67d01fa5b2150d7c01a84230112a/apps/website/lib/feature/news/data/news_data_state.dart#L19-L23

**Comment by temoki** [comment]
🙋 こちらの issue にチャレンジさせてください！
