### ISSUE TITLE
[Contributor]: About us タブの SNS アイコンのダークモード対応

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#382]
### 関連するもの

App

### タスクの種類

Bug

### 概要

About us タブの次の SNS アイコンがダークモード対応できておらず、ダークモード時に見づらくなってしまっています。

- X
- Medium
- GitHub

公式のアイコンのガイドラインがある場合にはそれに従って対応してください。

### 参考文献

- Xについて | Xロゴ、ブランドガイドライン、ポストツール
  - https://about.x.com/ja/who-we-are/brand-toolkit
- Medium Logo Usage Guidelines | by Medium | Medium.design
  - https://medium.design/logos-and-brand-guidelines-f1a01a733592
- GitHub Brand Toolkit
  - https://brand.github.com/

**Comment by utisam** [comment]
🙋 

Medium の Icon ロゴが丸角になったのもあって、現状の円のアウトラインを消して更新しようと思っています。最終的に Web サイトと同様の `IconButton` になるのが良いかと思っていますがいかがでしょうか？

**Comment by blendthink** [comment]
@utisam 
> 🙋 

ありがとうございます！
アサインさせていただきました💡

> Medium の Icon ロゴが丸角になったのもあって、現状の円のアウトラインを消して更新しようと思っています。最終的に Web サイトと同様の `IconButton` になるのが良いかと思っていますがいかがでしょうか？

はい、認識合っております！
よろしくお願いいたします🙏

@Kurogoma4D 何かおかしなこと言ってたらツッコミお願いします🙏
