### ISSUE TITLE
[Contributor]: 各タブの右上の設定ボタンの Semantic Label 警告対応

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#384]
### 関連するもの

App

### タスクの種類

Improvement

### 概要

各タブの右上の設定ボタンに Semantic Label が設定されていないため警告が表示されています。

適切な Semantic Label を設定してください。

<img src=https://github.com/user-attachments/assets/42c3c57b-9b55-444e-a49c-859762008322 width=320 />

### 参考文献

https://www.digital.go.jp/resources/introduction-to-web-accessibility-guidebook
https://waic.jp/translations/WCAG21/Understanding/

**Comment by MrSmart00** [comment]
🙋
すいません。別Issueだと気付かずに #516 で一緒に対応しちゃいました🙇‍♂️

**Comment by blendthink** [comment]
> 🙋 すいません。別Issueだと気付かずに #516 で一緒に対応しちゃいました🙇‍♂️

いえいえ、ご対応とても嬉しいです🥰 ありがとうございます！
