### ISSUE TITLE
[Contributor]: コントリビューター一覧画面の下部の余白調整

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#385]
### 関連するもの

App

### タスクの種類

Improvement

### 概要

コントリビューター一覧画面の下部の余白があまりなく、詰まって見えてしまっています。
`Scaffold` の `body` を `SafeArea` で囲って適切に余白が設定されるようにしてください。

<img src=https://github.com/user-attachments/assets/af9962ea-b58a-4f14-820e-f8791241384b width=320 />

**Comment by trashfeed** [comment]
🙋
