### ISSUE TITLE
[Contributor]: スポンサー一覧画面の Semantic Label 警告対応

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#389]
### 関連するもの

App

### タスクの種類

Improvement

### 概要

スポンサー一覧画面のリストアイテムに Semantic Label が設定されていないため警告が表示されています。

適切な Semantic Label を設定してください。

<img src=https://github.com/user-attachments/assets/7d081c98-cddb-4a1f-8fd4-39af856b453a width=320 />

### 参考文献

https://www.digital.go.jp/resources/introduction-to-web-accessibility-guidebook
https://waic.jp/translations/WCAG21/Understanding/

**Comment by MrSmart00** [comment]
🙋
