### ISSUE TITLE
[Contributor]: スタッフメンバー一覧画面の下部の余白調整

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#391]
### 関連するもの

App

### タスクの種類

Improvement

### 概要

スタッフメンバー一覧画面の下部の余白があまりなく、詰まって見えてしまっています。
`Scaffold` の `body` を `SafeArea` で囲って適切に余白が設定されるようにしてください。

<img src=https://github.com/user-attachments/assets/8afeda34-c073-4d0e-be7f-beac39808e59 width=320 />

**Comment by trashfeed** [comment]
🙋
