### ISSUE TITLE
[Contributor]: スポンサー一覧画面の下部の余白調整

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#392]
### 関連するもの

App

### タスクの種類

Improvement

### 概要

コントリビューター一覧画面の下部の余白があまりなく、詰まって見えてしまっています。
`Scaffold` の `body` を `SafeArea` で囲って適切に余白が設定されるようにしてください。

<img src=https://github.com/user-attachments/assets/c337d016-3bb2-4a1b-905c-6e32b6b47cc8 width=320 />

**Comment by trashfeed** [comment]
🙋
