### ISSUE TITLE
[Contributor]: コントリビューター一覧のタップイベント

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#395]
### 関連するもの

App

### タスクの種類

Feature

### 概要

コントリビューター一覧のリストアイテムをタップしたら、コントリビューターの GitHub アカウントページを表示できるように外部アプリを開くようにしてください。（可能であれば GitHub App を開く）

<img src=https://github.com/user-attachments/assets/ddccbfc9-1d6c-41ac-964c-b9a7b4a8e790 width=320 />

**Comment by ham-burger** [comment]
🙋
