### ISSUE TITLE
[Contributor]: スタッフメンバー一覧のタップイベント

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#396]
### 関連するもの

App

### タスクの種類

Feature

### 概要

スタッフメンバー一覧のリストアイテムをタップしたら、スタッフメンバーの GitHub アカウントページを表示できるように外部アプリを開くようにしてください。（可能であれば GitHub App を開く）

<img src=https://github.com/user-attachments/assets/86085f6c-be13-47c6-a948-bdf136035651 width=320 />

**Comment by mottox2** [comment]
🙋
