### ISSUE TITLE
[Contributor]: コントリビューター一覧をコントリビューション数順に並び替えて表示

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#397]
### 関連するもの

App, Website, Data

### タスクの種類

Feature

### 概要

コントリビューター一覧をコントリビューション数が多い順に表示されるように並び替えて表示してください。
`ContributorRepository` の `fetchContributors()` の処理を修正してください。

<img src=https://github.com/user-attachments/assets/ddccbfc9-1d6c-41ac-964c-b9a7b4a8e790 width=320 />

### 参考文献

https://supabase.com/docs/reference/dart/order

**Comment by trashfeed** [comment]
🙋
