### ISSUE TITLE
[Contributor]: コントリビューター一覧に草を生やす

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#398]
### 関連するもの

App

### タスクの種類

Feature

### 概要

コントリビューター一覧にデータとしてコントリビューション数は渡ってきますが、現状は何も表示していません。

デザインは要相談ですが、コントリビューション数を GitHub のアカウントページのように表現していただければと思います。（本物の草を生やしていただいてもOKです）

<img src=https://github.com/user-attachments/assets/ddccbfc9-1d6c-41ac-964c-b9a7b4a8e790 width=320 />

**Comment by masa-futa** [comment]
🙋‍♂️

**Comment by masa-futa** [comment]
@blendthink 
お疲れ様です！

こちら面白そうだったのでやらせてください🙏
以下デザイン考えてみたのですが、
草を生やそうかなと考えており、２パターンほど考えてみたのですがどうでしょうか🙏

※端末サイズに応じて表示する草数は変動するかもしれませんが、三列で収まらない場合は「+42」の様に末尾に表示させる様にしようかと考えております。
![Image](https://github.com/user-attachments/assets/5abac093-0f35-4401-84ea-8d8df81e1585)

**Comment by blendthink** [comment]
@masa-futa 
お疲れ様です！

> こちら面白そうだったのでやらせてください🙏

ぜひ、お願いいたします 🙌 

> 以下デザイン考えてみたのですが、
> 草を生やそうかなと考えており、２パターンほど考えてみたのですがどうでしょうか🙏
> ※端末サイズに応じて表示する草数は変動するかもしれませんが、三列で収まらない場合は「+42」の様に末尾に表示させる様にしようかと考えております。

わぁぁぁとてもステキなご提案ありがとうございます✨
個人的には枠線バージョンが好みではありますが @Kurogoma4D さん的にはいかがでしょうか？

**Comment by Kurogoma4D** [comment]
ご提案ありがとうございます！
自分も枠線のほうが良さそうに思いました👍
