### ISSUE TITLE
[Contributor]: About画面のGitHubアイコンのタップイベント

### ISSUE THREAD

**Issue by TK-Guitar** [FlutterKaigi/2024#415]
### 関連するもの

App

### タスクの種類

Feature

### 概要

About画面のGitHubアイコンタップ時の処理を、FlutterKaigi2024のGitHubページのURLを指定した外部ブラウザ起動処理に置き換えてください。
（可能であれば GitHub App を開く）

### 参考文献

![X](https://github.com/user-attachments/assets/ce1e4d80-417a-4c91-add2-896c2b08ad06)

**Comment by miyasic** [comment]
🙋

こちらのissueやってみたいです！
