### ISSUE TITLE
[Contributor]: About画面のXアイコンのタップイベント

### ISSUE THREAD

**Issue by TK-Guitar** [FlutterKaigi/2024#416]
### 関連するもの

App

### タスクの種類

Feature

### 概要

About画面のXアイコンタップ時の処理を、FlutterKaigi2024のXプロフィールページのURLを指定した外部ブラウザ起動処理に置き換えてください。
（可能であれば X App を開く）

XのURLは以下となります。
https://x.com/FlutterKaigi

### 参考文献

![Image](https://github.com/user-attachments/assets/7ed23fec-e16b-4baa-ba5c-87d66bc19cf3)

**Comment by iseruuuuu** [comment]
🙋
最近はあまり触れていないのと体調に波があるため途中でアサインから外してしまうかもしれませんが、せっかくなので取り組みたいと思いました🙇

**Comment by iseruuuuu** [comment]
[メモ]
以下のことをPRにて伝えておく

- ビルドしてから一回目のXを押した時にちゃんと「 X を開く」的なダイアログが出現したが、それ以降は開かずにいた
- XやFlutterKaigiアプリを削除してみたが変わらず

**Comment by iseruuuuu** [comment]
途中経過メモ
- iOSアプリでは行けてそう

https://github.com/user-attachments/assets/9daf0b46-7649-4851-b242-039740e894b1


https://github.com/user-attachments/assets/7a0e60a7-17cf-4e57-a3a8-4453a6d60cac
