### ISSUE TITLE
[Contributor]: About画面のMediumアイコンのタップイベント

### ISSUE THREAD

**Issue by TK-Guitar** [FlutterKaigi/2024#417]
### 関連するもの

App

### タスクの種類

Feature

### 概要

About画面のMediumアイコンタップ時の処理を、FlutterKaigi2024のMediumプロフィールページのURLを指定した外部ブラウザ起動処理に置き換えてください。

MediumのURLは以下となります。
https://medium.com/flutterkaigi

### 参考文献

![Image](https://github.com/user-attachments/assets/56329c0e-1a4f-4020-86a0-183a68e738f5)

**Comment by ham-burger** [comment]
🙋
