### ISSUE TITLE
 [Contributor]: About ページのカレンダーのタップイベント

### ISSUE THREAD

**Issue by TK-Guitar** [FlutterKaigi/2024#418]
### 関連するもの

App

### タスクの種類

Feature

### 概要

ボタン（赤枠）をタップ時に、Googleカレンダーへのリンクを表示し、iOS端末では[add_2_calendar](https://pub.dev/packages/add_2_calendar)機能を使ってイベントを追加できるようにしてください。

2023年のカレンダーのイベント追加ロジックも参考していただけますと幸いです。
https://github.com/FlutterKaigi/conference-app-2023/issues/164
https://github.com/FlutterKaigi/conference-app-2023/pull/250

### 参考文献

<img src="https://github.com/user-attachments/assets/c4e4f7d4-e98a-452c-a755-6b44a8ebc160" width="50%" />

<img src="https://github.com/user-attachments/assets/b0f12258-2c00-41ca-9825-e90dc56e22c9" width="50%" />

**Comment by masa-futa** [comment]
🙋

**Comment by masa-futa** [comment]
@TK-Guitar 
お疲れ様です！
一点仕様の確認をさせてください。
カレンダーに表示する文言等ですが、以下の想定で齟齬ないでしょうか。
```
件名(title)：FlutterKaigi 2024
詳細(description)：FlutterKaigi は世界中の Flutter/Dart を愛する人々が集まる場所です。知識や情熱を共有する場を提供することを目的に、Flutter/Dart に魅せられた有志によって実行委員会が組織されています。初心者から上級者までが集まり、Flutter/Dart について学び、語り合い、楽しむことができます。イベントの開催は日本になりますが、インターネット配信を活用し、全世界に発信しています。
場所(location)：有明セントラルタワーホール&カンファレンス
日時(start,end)：2024/11/21 ~ 2024/11/22
```

2023年の対応ではイベント毎に、文言等が変動していましたが、
2024年では、本イベントに関してのカレンダー登録を実施する仕様に見受けられたため、固定文言で問題ないかを気にしております。

**Comment by blendthink** [comment]
> @TK-Guitar お疲れ様です！ 一点仕様の確認をさせてください。 カレンダーに表示する文言等ですが、以下の想定で齟齬ないでしょうか。
> 
> ```
> 件名(title)：FlutterKaigi 2024
> 詳細(description)：FlutterKaigi は世界中の Flutter/Dart を愛する人々が集まる場所です。知識や情熱を共有する場を提供することを目的に、Flutter/Dart に魅せられた有志によって実行委員会が組織されています。初心者から上級者までが集まり、Flutter/Dart について学び、語り合い、楽しむことができます。イベントの開催は日本になりますが、インターネット配信を活用し、全世界に発信しています。
> 場所(location)：有明セントラルタワーホール&カンファレンス
> 日時(start,end)：2024/11/21 ~ 2024/11/22
> ```
> 
> 2023年の対応ではイベント毎に、文言等が変動していましたが、 2024年では、本イベントに関してのカレンダー登録を実施する仕様に見受けられたため、固定文言で問題ないかを気にしております。

@masa-futa 
返信遅くなってしまい申し訳ありません 🙏 
ご提案いただいた固定文言で問題ありません！
よろしくお願いいたします！！
