### ISSUE TITLE
[App-Staff]: FlutterKaigi の紹介

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#43]
### 達成したいこと

FlutterKaigi とは何かを知ることができる。

**Comment by blendthink** [comment]
@keitokusano 
いったん、文言は昨年のものでお願いします！

- https://github.com/FlutterKaigi/conference-app-2023/blob/17ffd4559d6bb9807e226914a0c7e1491e62ae36/lib/l10n/localization_ja.dart#L245C14-L246
- https://github.com/FlutterKaigi/conference-app-2023/blob/17ffd4559d6bb9807e226914a0c7e1491e62ae36/lib/l10n/localization_en.dart#L250-L251

また、ロゴは Figma から SVG でダウンロードして使うようにお願いします！

@Kurogoma4D 何か認識違いあればツッコミお願いします 🙏

**Comment by Kurogoma4D** [comment]
@keitokusano 
https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=323-180&t=Xr7miM1WQZo5vH24-4

一応ロゴの出力はここからお願いします～

**Comment by keitokusano** [comment]
残作業メモ
- [ ] 左上のロゴ
- [ ] 最上部の真ん中のFlutterKaigiのロゴ
- [ ] XとMidiuemとGithubのアイコン
- [ ] arb ファイル対応
