### ISSUE TITLE
[App-Staff]: OSS のライセンス一覧

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#47]
### 達成したいこと

アプリで使用している OSS のライセンス一覧を知ることができる。

**Comment by TK-Guitar** [comment]
LicensePageを使用して実装する
https://api.flutter.dev/flutter/material/LicensePage-class.html

**Comment by TK-Guitar** [comment]
これからPR上げる予定ですが、去年のものを参考にこんな感じ想定です。
一先ずWidgetのどこかしらのデバッグで遷移できるように想定できるようにしときます。

> LicensePage(
> 　　applicationName: 'FlutterKaigi 2024 Official App',
> ),

**Comment by TK-Guitar** [comment]
これも関連してる
https://github.com/FlutterKaigi/2024/issues/48

**Comment by TK-Guitar** [comment]
PRあげました
https://github.com/FlutterKaigi/2024/pull/112

**Comment by TK-Guitar** [comment]
@blendthink 
以下のPRがマージされたので、issueをクローズしても大丈夫でしょうか？
https://github.com/FlutterKaigi/2024/pull/112

**Comment by blendthink** [comment]
> @blendthink 
> 
> 以下のPRがマージされたので、issueをクローズしても大丈夫でしょうか？
> 
> https://github.com/FlutterKaigi/2024/pull/112

@TK-Guitar 
はい、大丈夫です！
