### ISSUE TITLE
[App-Staff]: OSS のライセンス詳細

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#48]
### 達成したいこと

アプリで使用している OSS のライセンスの詳細情報を知ることができる。

**Comment by TK-Guitar** [comment]
PRあげました
https://github.com/FlutterKaigi/2024/pull/112

**Comment by TK-Guitar** [comment]
@blendthink 
以下のPRがマージされたので、issueをクローズしても大丈夫でしょうか？
https://github.com/FlutterKaigi/2024/pull/112

**Comment by blendthink** [comment]
> @blendthink 
> 
> 以下のPRがマージされたので、issueをクローズしても大丈夫でしょうか？
> 
> https://github.com/FlutterKaigi/2024/pull/112

@TK-Guitar 
はい、大丈夫です！
