### ISSUE TITLE
[Contributor]: About画面の各アイコンのエフェクトが反映される領域が小さい

### ISSUE THREAD

**Issue by keitokusano** [FlutterKaigi/2024#482]
### 関連するもの

App

### タスクの種類

Bug

### 概要

動画の通りエフェクトが反映される領域が狭いため、修正してください。
動画では、X のアイコンとなっておりますが、他2つも同様となります。
当 issue を対応するためには、先に issue #415  の対応が必要となります。
もし可能でしたら、まとめて対応してくださると大変助かります。

<video src="https://github.com/user-attachments/assets/4a320548-c9c8-41ee-aa1f-71ea7418bae2" width="300" >

**Comment by iseruuuuu** [comment]
🙋
こちらのタスクですが時間がかかるかもしれませんがトライしてみたいです！
