### ISSUE TITLE
[Contributor]: Day 1 と Day 2 のスクロール位置が同期されてしまっている

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#491]
### 関連するもの

App

### タスクの種類

Bug

### 概要

セッション一覧画面の Day 1 と Day 2 のスクロール位置が同期されてしまっていました。
スクロールを独立するように修正してください。

https://github.com/user-attachments/assets/fec58f93-3ab4-4424-a88c-891f12e39bb2

### 参考文献

↓ futaboo さんよりご指摘いただきました 🙏 
https://x.com/futabooo/status/1855158007556186610

**Comment by masa-futa** [comment]
🙋
