### ISSUE TITLE
[App-Staff]: 各セッションへのフィードバック・感想

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#53]
### 達成したいこと

各セッションの登壇者へフィードバックや感想を送ることができる。

**Comment by TK-Guitar** [comment]
ここのデザインがないので、kurogomaさんに相談する

![スクリーンショット 2024-10-15 19 51 54](https://github.com/user-attachments/assets/1a8ee6ac-de7b-4727-8450-bbeeaa71a925)

**Comment by blendthink** [comment]
検討内容
https://flutterkaigi.slack.com/archives/C06MHU8J56K/p1730281922984589
